services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ghostsend_backend
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=host.docker.internal;Port=5432;Database=ghostsend;Username=admin;Password=supersecretpassword
      - MinioSettings__ServiceURL=http://host.docker.internal:9000
      - MinioSettings__AccessKey=minioadmin
      - MinioSettings__SecretKey=minioadmin
      - MinioSettings__BucketName=ghostsend-files
      - MinioSettings__ForcePathStyle=true
      - FileSettings__MaxFileSizeInBytes=10737418240
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:8080"
    restart: always
